- abagen/io.py
Loading data using the `abagen.io` functions that rely on parquet cause some downstream errors when parquet isn't installed. That is, the columns and index name of `microarray` and `pacall` dataframes weren't being set correctly if the parquet version of these files didn't exist, resulting in indexing errors during a call to `get_expression_data()`.
Since parquet is _supposed_ to be optional, this is obviously undesired. This commit ensures that columns / index names are set correctly regardless of whether they are loaded with `parquet` or `pandas`.
> [FIX] Resolves dataframe formatting issue

- abagen/allen.py
- abagen/correct.py
- abagen/info.py
- abagen/process.py
- abagen/tests/test_correct.py
- requirements.txt
Adds functions for correcting distance-dependent spatial effect of correlated gene expression arrays (`abagen.correct.remove_distance()`) and for discard genes that do not have a high differential stability across donors (`abagen.correct.keep_stable_genes()`). 
The latter function required adding the ability to return donor-level expression arrays from `abagen.get_expression_data()`, so this closes #9.
> [ENH] Adds `abagen.correct` for postprocessing

- abagen/correct.py
- abagen/tests/test_correct.py
`remove_distance()` now assumes that a square coexpression array is provided rather than generating it from the data.
> [REF] Changes `remove_distance()` inputs

- abagen/correct.py
- abagen/tests/test_correct.py
- abagen/utils.py
Allows users to specify labels to consider in `abagen.correct.remove_distance()` if atlas_info and atlas do not match.
> [ENH] Allow label exclusion in `remove_distance()`

- README.rst
- abagen/allen.py
- abagen/correct.py
- abagen/tests/conftest.py
- abagen/tests/test_allen.py
- abagen/tests/test_correct.py
- abagen/utils.py
- docs/usage.rst
Closes #35.
Calling `abagen.get_expression_data()` no longer requires users to pass a `files` object obtained from `abagen.fetch_microarray_data()` -- it just calls it automatically!
> [REF] Updates get_expression_data()

- abagen/io.py
If the installed version of pandas is too old then trying to call `pd.io.parquet.get_engine('fastparquet')` fails with an AttributeError because `pandas.io` does not have a parquet module. Since all the parquet nonsense is optional (and only really a small improvement in terms of load-time...), it doesn't make sense to pin the new pandas dependency, so we're just gonna go with catching the warning and ignoring parquet.
> [FIX] Catches AttributeError w/pandas fastparquet

- abagen/allen.py
Closes #43.
Should remove the `RuntimeWarning` experienced when running the example code on the ReadTheDocs site!
> [FIX] Removes RuntimeWarning in example code

- README.rst
- abagen/allen.py
- abagen/datasets.py
- abagen/info.py
- abagen/mouse/utils.py
- docs/conf.py
- docs/usage.rst
Closes #37.
Also updates all http references to https.
> [DOC] Update refs and http

- abagen/mouse/io.py
- abagen/mouse/tests/test_io.py
> Fixed abagen.mouse column ordering

- .travis.yml
- abagen/allen.py
- abagen/info.py
- docs/installation.rst
Begins to address (but certainly does not close) #36.
So that you know what's happening and get some stats about things when you run the functions!
> [DOC] Adds logging to workflow functions

- abagen/allen.py
- abagen/mouse/mouse.py
- abagen/mouse/tests/test_mouse.py
- abagen/mouse/tests/test_structure.py
- abagen/process.py
Closes #63 
Addresses pandas v0.25.0 deprecation warnings for `.get_values()` method on `Series` and `DataFrames`. Replaces all references with `numpy.asarray()`
> [REF] Removes .get_values() references

- abagen/datasets.py
- abagen/tests/test_datasets.py
Closes #44.
Adapts functionality from `nilearn` to accept a more liberal `data_dir` specification in `abagen.datasets.fetch_microarray()`. If `data_dir` is not provided the function now defaults to storing datasets in `$HOME/abagen-data`.
> [REF] Changes data directory locator for abagen data

- abagen/allen.py
- abagen/probes.py
- abagen/process.py
- abagen/tests/test_probes.py
- setup.cfg
Closes #51.
Moves all functions operating on probes to `abagen.probes` module (i.e., `reannotate_probes()` and `filter_probes()`, previously in `abagen.process`) and adds new probe selection methods (previously limited to differential stability).
New selection methods have been integrated into primary workflow (i.e., `abagen.get_expression()`) via the optional `probe_selection` keyword argument. Relevant references and description of the different methods have been added to the Notes of the doc-strings.
To do:
> [REF,ENH] Adds new abagen.probes module

- abagen/process.py
- docs/user_guide/parcellations.rst
Closes #79.
Adds brainstem (and other) structures to `abagen.process.ONTOLOGY` dictionary for better matching with structural classes when users provide an `atlas_info` argument to `abagen.get_expression_data()`.
To Do:
> [REF] Adds brainstem to abagen.process ontology

- abagen/cli/run.py
- abagen/tests/conftest.py
- abagen/tests/test_cli.py
- docs/cli.rst
- docs/conf.py
- docs/index.rst
- docs/requirements.txt
- setup.cfg
Closes #70 
Adds a command-line interface for the primary workflow available through the `abagen.get_expression_data()` function so that users don't have to open a Python instance if they're more comfortable with shell scripting.
To do:
> [ENH] Adds CLI for `abagen.get_expression_data` functionality

- abagen/datasets/__init__.py
- docs/api.rst
- docs/requirements.txt
For some reason the use of the `.. include` directive in the index.rst of the docs is breaking the API section of the docs (basically, the entirety of the README is duplicated in the API). This resolves that issue and makes a few minor aesthetic updates to the API.
Additionally, ReadTheDocs is using sphinx version 1.8.1 (or something similar) which is rendering the CLI argument tables weirdly. This pins the Sphinx version to >=2.0.
> [FIX] Fixes broken include directive in API reference

- abagen/allen.py
- abagen/io.py
- abagen/probes.py
- abagen/samples.py
- abagen/tests/test_io.py
By default if any of the `abagen.io` functions were passed a dataframe as input (instead of the expected filepath) it would return a copy of the dataframe. Unfortunately, this is often unwarranted -- there are few instances in `abagen` where a copy of the original dataframe is needed and the original can be used, instead.
This PR adds a `copy` parameter (False, by default) to all the `abagen.io` functions, and updates a few occasions when those functions are called and copying the input dataframe (if it is, indeed, a dataframe) is needed.
> [REF] abagen.io functions don't copy dataframes by default

- .travis.yml
- MANIFEST.in
- setup.cfg
Wasn't bundling package data for certain installation types. Partly due to typos in the `setup.cfg`, partly due to a missing recursive-include in the MANIFEST.in.
Also modify travis tests so they don't happen inside the repository directory, which I think was hiding these issues.
> [FIX] Installation not correctly bundling package data

- abagen/allen.py
- abagen/tests/test_allen.py
Closes #5 
When supplying only one donor via the `donor` parameter to `abagen.get_expression_data()` and using the default `probe_selection` method ('diff_stability') a really cryptic error was raised. This catches that specific combination and raises a more helpful error.
Also adds tests for the errors raised by `abagen.get_expression_data()`.
> [REF] Fixes one-donor bug in get_expression_data()

- abagen/samples.py
Closes #116.
Specify engine='python' in pandas query in drop_mismatch
function (in samples.py file) since engine='numexpr' cannot
handle NaNs and the later is the default option.
> [FIX] specify engine='python' in pandas queries

- abagen/samples.py
- abagen/tests/test_allen.py
- abagen/utils.py
Deprecated as of 3.0 in favor of `np.asarray(img.dataobj)`.
> [REF] Removes `.get_data()` nibabel calls

- abagen/allen.py
> make count dataframe float > int

- abagen/allen.py
- abagen/correct.py
Can now optionally suppress warnings in `correct.normalize_expression` since, in many cases, the resulting errors will be removed post-normalization.
> [REF] Adds option to suppress norm warnings

- abagen/allen.py
- abagen/correct.py
- abagen/tests/test_correct.py
Fixes an error in `get_expression_data()` when `exact=False` and there was only one ROI missing expression data.
Also adds an option to be able to get gene stability estimates.
> [FIX,ENH] Error in get_expression_data, gene stability calculation

- .circleci/config.yml
- abagen/__init__.py
- abagen/allen.py
- abagen/datasets/__init__.py
- abagen/datasets/fetchers.py
- abagen/io.py
- abagen/tests/conftest.py
- abagen/tests/datasets/test_fetchers.py
- abagen/tests/test_io.py
- docs/api.rst
Closes #98 
Adds new functions for fetching and loading RNAseq data. Modifies other related functions / updates some doc-strings as necessary (e.g., `io.read_annotation` doc-string).
The changes to `abagen.get_expression_data()` (i.e., the call to `fetch_rnaseq`) should never actually be trigged, currently, until #137 is addressed (we explicitly check the provided `probe_selection` method against `probes_.SELECTION_METHODS`, and since 'rnaseq' isn't a valid option it will error out before hitting the fetcher).
> [ENH] Adds fetchers / loaders for RNAseq data

- abagen/allen.py
- abagen/correct.py
- abagen/datasets/fetchers.py
- abagen/io.py
- abagen/probes_.py
- abagen/samples_.py
- abagen/tests/datasets/test_fetchers.py
- abagen/tests/test_allen.py
- abagen/tests/test_correct.py
- abagen/tests/test_io.py
- abagen/tests/test_probes.py
- abagen/tests/test_samples.py
- abagen/tests/test_utils.py
- abagen/utils.py
- docs/api.rst
- docs/user_guide/download.rst
Closes #137 
Oof. This is a pretty massive re-factor to accommodate a new `probe_selection` method for the `abagen.get_expression_data()` pipeline: `'rnaseq'`! I had to change the data structure returned from all `fetch_X()` functions, which had pretty dramatic effects for a lot of downstream functionality.
Currently not sure how to test this functionality since this method is only available for two donors (neither of which are fetched in the current testing suite) 🤷‍♂ Will try and think of something.
> [ENH,REF] Adds RNAseq probe selection method

- abagen/io.py
Not just when a `pandas.DataFrame` is passed, but when a filepath is passed, too!
> [FIX] Always remap annotation dataframe cols

- abagen/datasets/fetchers.py
- requirements.txt
- setup.cfg
Based on #150.
The `errors` kwarg for `pandas.DataFrame.rename` was only introduced in pandas v0.25.
> [MNT] Pin minimum pandas version to 0.25

- abagen/__init__.py
- abagen/allen.py
- abagen/correct.py
- abagen/tests/test_allen.py
- docs/api.rst
- docs/usage.rst
- docs/user_guide/mask.rst
- docs/user_guide/normalization.rst
Closes #46.
Adds function `abagen.get_samples_in_mask(mask)` which allows users to provide a mask (binary or otherwise 🤷‍♂️) and all samples within `tolerance` of mask boundaries are returned (along with MNI coordinates of samples). If no mask is provided, (i.e., `mask=None`) all available tissue samples are returned instead.
This required adding a `region_agg=None` option to `abagen.get_expression_data()`, though I am choosing not to document this functionality in favor of having people use `get_samples_in_mask()` directly so that the relevant sample coordinates are returned alongside expression data.
To do:
> [ENH] Allows users to get microarray samples in mask

- .azure-pipelines/windows.yml
- azure-pipelines.yml
Trying to fix azure testing...
> [TEST] Change Azure VM image to fix SSL

- abagen/io.py
- abagen/tests/test_samples.py
- abagen/utils.py
Addresses #166 
As of pandas 1.2.0 when `pd.read_csv` is given a DataFrame object it throws a `TypeError` (instead of a `ValueError`). This PR adjusts all previously handled exceptions to deal with the new error type and fixes other errors stemming from new version issues.
> [FIX] Read_csv error when using pandas > 1.2.0

- abagen/allen.py
- abagen/correct.py
- abagen/tests/test_correct.py
- docs/user_guide/normalization.rst
Adds `norm_structures` parameter to `abagen.get_expression_data()`, which controls whether gene normalization occurs globally (across all samples) or independently for different structural classes (i.e., cortex, subcortex/brainstem, cerebellum).
> [ENH] Add `norm_structures` parameter

- abagen/allen.py
- abagen/samples_.py
- abagen/tests/test_samples.py
- docs/user_guide/expression.rst
Closes #97.
Adds single hemisphere mirroring (i.e., left-to-right *or* right-to-left) by changing `lr_mirror` from a boolean to a method-based parameter. Tests and documentation have been updated to reflect new usage. 
A `DeprecationWarning` has been added if `lr_mirror` is provided as a boolean to alert users to the new format.
> [REF] Modifies `lr_mirror` to accept single hemisphere mirroring

- abagen/allen.py
- abagen/matching.py
- abagen/tests/test_correct.py
- abagen/tests/test_matching.py
Closes #6.
This PR updates how "inexact" matching is performed in the `abagen.get_expression_data()` workflow (i.e., when `exact=False`). This matching is now constrained by hemisphere + structural class designation, as designated in `atlas_info`; if `atlas_info` is not provided then the centroid matching is performed as before.
> [REF] Constrains centroid matching by atlas_info

- azure-pipelines.yml
> [TEST] Add py3.8 to azure tests

- abagen/allen.py
- abagen/samples_.py
- abagen/tests/test_samples.py
Fixes an issue where certain structures are bilateral (but the ontology has the hemisphere listed as "NaN"). Also suppresses a warning for `pd.DataFrame.set_axis()` by explicitly passing the `inplace` parameter.
> [FIX] Nan hemisphere designation

- abagen/allen.py
- abagen/cli/run.py
- abagen/data/donor_info.csv
- abagen/datasets/__init__.py
- abagen/images.py
- abagen/probes_.py
- abagen/reporting.py
- abagen/samples_.py
- abagen/tests/datasets/test_fetchers.py
- abagen/tests/test_allen.py
- abagen/tests/test_images.py
- abagen/tests/test_reporting.py
- docs/api.rst
- docs/usage.rst
- docs/user_guide/reporting.rst
Adds a `return_report` option (and the `abagen.reporting` module) to auto-generate Methods sections detailing the processing performed with `abagen.get_expression_data()`.
Also adds some smoke tests and some documentation to describe the new functionality.
> [ENH] Add Methods auto-generation

- abagen/matching.py
- abagen/reporting.py
- abagen/tests/test_matching.py
Wherein negative tolerance will ensure samples are not matched to vertices that are more than `-tolerance` mm away (rather than `tolerance` operating as a standard deviation threshold).
> [REF] Allow negative tolerance for surfaces

- abagen/allen.py
- abagen/cli/run.py
- abagen/io.py
- abagen/samples_.py
- abagen/tests/test_samples.py
- docs/user_guide/download.rst
- docs/user_guide/expression.rst
As in Burt et al., 2018, *Nature Neuroscience*. By default this is turned off, but can be modified with the `sim_threshold` parameter, which operates as a standard deviation threshold.
> [ENH] Adds interareal similarity thresholding

- abagen/probes_.py
- abagen/tests/test_probes.py
The index of the expression dataframes were being lost when `probe_selection='average'` was used due to a `.join()` function, causing everything downstream to break. This fixes that issue and adds a test to check for it in the future.
> [FIX] Fixes 'average' probe selection bug

- abagen/datasets/fetchers.py
- abagen/images.py
- abagen/matching.py
- abagen/tests/datasets/test_fetchers.py
- abagen/tests/test_images.py
- abagen/tests/test_matching.py
- abagen/utils.py
- docs/user_guide/parcellations.rst
Makes it much easier to specify non-standard atlases / surfaces, which benefits construction of `AtlasTree` objects and enables better use of graph representation of surfaces
> [ENH] Add geometry/space option to check_atlas

- abagen/allen.py
Closes #188 
Removes the call to `samples_.drop_mismatch_samples()` in `abagen.get_samples_in_mask()` which was causing coordinates to be out-of-alignment with returned expression data when donor-specific masks were provided. This requires modifying the return `coords` array to be a dataframe (with columns 'x', 'y', and 'z'), but this should not be a major issue.
I've also modified the returned `expression` dataframe to have a multi-index with both `'well_id'` and `'label'` levels (when `region_agg=None` is passed to `abagen.get_expression_data()`). This is useful for many reasons.
> [REF] Fix coordinates of get_samples_in_mask

- abagen/allen.py
- abagen/cli/run.py
- abagen/images.py
- abagen/matching.py
- abagen/samples_.py
- abagen/tests/test_correct.py
Closes #190.
This modifies the procedure by which sample coordinates are "floored" before matching to regions in the user-provided atlas(es); the flooring procedure is only performed when group atlases are supplied, and rather than flooring we simply round down to the nearest voxel.
> [FIX] Error with donor-specific atlases and tolerance=0

- abagen/images.py
- abagen/reporting.py
When calling `abagen.get_expression_data()` with `return_report=True` and `verbose=True` there was an error in the log. The returned reports were accurate (phew), but because we were calling `images.coerce_atlas_to_dict()` multiple times the logger was being called multiple times and therefore reporting (inconsistently) what type of atlas was being used (MNI vs donor-specific). This clears that up.
> [FIX] Fixes logger error w/reports

- abagen/images.py
- docs/user_guide/expression.rst
If images provided to `images.leftify_atlas()` weren't in RAS orientation then the return atlas was not correctly zeroed out. This modification re-orients the atlas to RAS, zeros out the right hemisphere, then re-re-orients the atlas back to its original format.
> [REF] Re-orient img in `leftify_atlas()`

- abagen/matching.py
- abagen/tests/test_matching.py
Hopefully addresses #196 
Adds better handling of volumetric atlas grids with non-integer steps (i.e., voxel sizes) and non-integer affine offsets. Need to add a few tests to confirm functionality but I think this should work...
> [REF] Handle atlases w/decimal vox sizes
