abagen/datasets.py
Minor stylistic updates to abagen.datasets, including updating doc-strings to specify that all donors can be downloaded at once.
=> [STY] Stylistic updates to abagen.datasets

README.md, abagen/__init__.py, abagen/datasets.py
Adds easy fetcher for DK atlas shipped with `abagen` (`abagen.fetch_desikan_killany()`) and updates example in README.md to use this atlas.
=> [ ENH ] Adds DK atlas fetcher and updates README.md

abagen/tests/test_allen.py, abagen/tests/test_utils.py, abagen/tests/utils.py
Adds more tests of `get_expression_data` to confirm different combinations of parameters still work.
=> [TEST] Updates tests

CODE_OF_CONDUCT.md, CONTRIBUTING.md, MANIFEST.in, README.rst, abagen/info.py, docs/installation.rst, docs/usage.rst, setup.cfg, setup.py
Fixes line breaks in CoC and CONTRIBUTING.md, updates installation and usage instructions, and clarifies title in README.rst
=> [DOC] Updates various documentation

.travis.yml, abagen/info.py
Pytest>=3.6 required for coverage reports. Updates to test environment handling.
=> [TEST] Fix pytest version and update travis

.gitignore, abagen/mouse/tests/test_mouse.py
This is why you don't make changes from the GitHub UI without testing...
=> [TEST] Fixes tests

abagen/datasets.py
Don't try and download them from the internet---they're not changing anytime soon :man_shrugging:
=> [REF] Use cached alleninf coordinates only

.travis.yml, abagen/mouse/gene.py, abagen/mouse/mouse.py, abagen/mouse/structure.py, setup.cfg
Also overhauls .travis.yml to explicitly test doctests.
=> [FIX] Fixes doctest in abagen.mouse

abagen/allen.py
Moves left/right hemisphere mirroring of samples such that it occurs before probe filtering. This is an implementation decision with no "right" answer, but I think that if we're going to pretend the samples are mirrored we should assume they're mirrored right from the get-go.
=> [REF] Mirroring before probe filtering

.zenodo.json, docs/citing.rst, docs/conf.py
Addresses (but does not close) #104.
- Adds .zenodo.json so that releases have authors auto-populated
- Adds template for citation to docs -- needs to be updated once Zenodo integration is finalized!
=> [MNT] Adds framework for Zenodo integration

README.rst, abagen/info.py, docs/citing.rst, docs/index.rst
Closes #104.
- Adds Zenodo badge to README and updates citing.rst to auto-populate with latest Zenodo DOI citation
=> [MNT] Finishes Zenodo integration

.circleci/config.yml, dev_requirements.txt
Adds .circleci/config.yml in place of .travis.yml to try caching data between test builds. We'll see how it works....
=> [TEST] TravisCI --> CircleCI

abagen/data/donor_info.csv, abagen/datasets/fetchers.py
=> Add file with donor info

abagen/samples.py
Should fix fancy indexing error
=> [FIX] Coerce atlas dataobj to arr before indexing

.azure-pipelines/windows.yml, abagen/tests/cli/test_run.py, abagen/tests/datasets/test_utils.py, azure-pipelines.yml, setup.cfg
First pass at adding Azure pipelines for CI testing on Windows
=> [TEST] Adding Azure Pipelines

abagen/__init__.py, abagen/datasets/__init__.py, abagen/datasets/fetchers.py, docs/api.rst
Relates to #50
Adds fetcher for raw FreeSurfer data from Romero-Garcia et al., 2018
=> [ENH] Adds FreeSurfer data fetcher

azure-pipelines.yml
=> [TEST] Fix Azure maybe?

abagen/allen.py
Should have from the beginning but didn't test things correctly 🤦‍♂
=> [FIX] Allow 'common' for donor_probes method

docs/user_guide/normalization.rst, docs/user_guide/probes.rst
Also fixes a broken function link in the docs!
=> [DOC] Adds Fulcher norm ref

README.rst, abagen/info.py
=> issue #139 readme fix

abagen/correct.py
=> issue #80 doc string fix

abagen/mouse/utils.py
`info = get_structure_info(id=22, verbose=True, attributes=["name", "acronym"])
print(info)
Querying https://api.brain-map.org/api/v2/data/Structure/query.json?criteria=[id$eq22],ontology[id$eq1]&only=name,acronym,id&...
name acronym
id                                              
22  Posterior parietal association areas    PTLp`
=> issue #73 unquote url

.circleci/config.yml
py3.8 tests added in ci according issue #157
=> issue #157

.circleci/config.yml, abagen/tests/test_correct.py
test_correct.test_resid_dist
test_correct.test_keep_stable_genes
with parametrize
=> test_correct.test_resid_dist

abagen/allen.py, abagen/cli/run.py, abagen/tests/cli/test_run.py
Closes #159 .
CLI was missing a few options that had been added to the main `get_expression_data()` workflow over the past few cycles. This brings the CLI into sync with the main workflow, and updates the documentation of both to reflect recent changes.
=> [REF] Updates CLI to match main workflow

abagen/mouse/io.py
Uses default $HOME/abagen-data instead of site-packages
=> [REF] Updates mouse data cache location

CONTRIBUTING.md, README.rst, abagen/info.py, docs/contributing.rst, docs/installation.rst
=> [DOC] Updates master refs to main

abagen/allen.py, abagen/reporting.py, abagen/tests/test_reporting.py, docs/user_guide/reporting.rst
Makes some minor changes to the `Report` class to better reflect the updated methodology of the new `missing` parameter.
=> [REF] Updates reports for `missing` param

abagen/probes_.py, abagen/samples_.py, abagen/utils.py
Due to the recent update in Pandas, some of the original code does not work because of deprecated functions like `append()`
=> Pandas Compatibility 

.github/workflows/tests.yml, .gitignore, abagen/tests/conftest.py, dev_requirements.txt
=> [FIX] Fix tests

docs/user_guide/download.rst, docs/user_guide/parcellations.rst
Resolve some critical confusions
=> [DOC] Update docs
